# -*- coding: utf-8 -*-
"""economics_forecasting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J37fFd8fHgqpDmuyVw9H-ugazLNeh7MW
"""

# Installation and importing necessary libraries
!pip install fredapi

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

import fredapi as fd

# Initializing FRED API with API key
fred=fd.Fred(api_key='518ef89a2c354e90783a439f260ee291')

data=fred.search('Consumer Price Index for All Urban Consumers: All Items in U.S. City Average')

data.head(10)

data['title'][0]

# Getting the CPI (Consumer Price Index) series and renaming it to 'values'
cpi=fred.get_series('CPIAUCSL')
cpi.name='values'

cpi

# Creating a DataFrame from the CPI series and resetting its index
df=pd.DataFrame(cpi).reset_index()

df

# Selecting data starting from 1989-01-01
df2=df[df['index']>'1989-01-01']

df2

# Creating a line plot
fig=px.line(df2, x='index', y='values', title='CPI Avg. 1990-2023')

fig.show()

# Renaming DataFrame columns to 'ds' and 'y' for Prophet library usage
df2=df2.rename(columns={'index':'ds', 'values':'y'})

df2

# Importing the Prophet library and creating a Prophet model
from prophet import Prophet

model=Prophet()
model.fit(df2)

# Creating a dataframe for the next 10 months with monthly frequency
future=model.make_future_dataframe(periods=10, freq='MS')

future.tail()

# Making predictions using the Prophet model for the future dataframe
result=model.predict(future)

result[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

fig=model.plot(result)

fig2=model.plot_components(result)

# Performing cross-validation to evaluate model performance
from prophet.diagnostics import cross_validation, performance_metrics

cv_results=cross_validation(model=model,
                            initial=pd.to_timedelta(30*20, unit='D'),
                            period=pd.to_timedelta(30*5, unit='D'),
                            horizon=pd.to_timedelta(30*12, unit='D')
                            )

cv_results['cutoff'] = pd.to_datetime('2023-11-01')

df_p=performance_metrics(cv_results)

df_p

from prophet.plot import plot_cross_validation_metric

fig=plot_cross_validation_metric(cv_results, metric='mae')

